[package]
name = "maplibre-style-spec"
version = "0.1.0"
edition = "2024"

[dependencies]
codegen.workspace = true
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "generate_spec"
path = "src/bin/generate_spec.rs"

[dev-dependencies]
insta.workspace = true
