name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-test:
    name: Unit test the server
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false, submodules: true }
      - run: cargo test
      - run: cargo test --doc
  lint:
    name: Lint the Rust code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy rustfmt
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false, submodules: true }
      - run: ls maplibre-style-spec/tests/
      - run: ls maplibre-style-spec/tests/upstream/
      - uses: taiki-e/install-action@cc60de1d6831d7e9c4342f618ce7a5d6a9f223a4 # v2.61.6
        # TODO: add cargo-sort once https://github.com/taiki-e/install-action/pull/997 is resolved
        with: { tool: 'just,cargo-binstall' }
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      - run: just env-info
      - run: just test-fmt
      - run: just clippy
  check:
    name: Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with: { persist-credentials: false, submodules: true }
      - uses: taiki-e/install-action@cc60de1d6831d7e9c4342f618ce7a5d6a9f223a4 # v2.61.6
        with: { tool: 'just' }
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      - run: just env-info
      - run: just check
      - run: just check-doc

  # This final step is needed to mark the whole workflow as successful
  # Don't change its name - it is used by the merge protection rules
  done:
    name: CI Finished
    runs-on: ubuntu-latest
    needs: [ check, lint, unit-test ]
    if: always()
    permissions: {}
    steps:
      - name: Result of the needed steps
        run: echo "${{ toJSON(needs) }}"
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        name: CI Result
        run: exit 1
