name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  unit-test:
    name: Unit test the server
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false, submodules: true }
      - run: cargo test
      - run: cargo test --doc
  lint:
    name: Lint the Rust code
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy rustfmt
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false, submodules: true }
      - uses: taiki-e/install-action@50708e9ba8d7b6587a2cb575ddaa9a62e927bc06 # v2.62.63
        # TODO: add cargo-sort once https://github.com/taiki-e/install-action/pull/997 is resolved
        with: { tool: 'just,cargo-binstall' }
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      - run: just env-info
      - run: just test-fmt
      - run: just clippy
  check:
    name: Check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - run: rustup update stable && rustup default stable
      - name: Checkout sources
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with: { persist-credentials: false, submodules: true }
      - uses: taiki-e/install-action@50708e9ba8d7b6587a2cb575ddaa9a62e927bc06 # v2.62.63
        with: { tool: 'just' }
      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
        if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
      - run: just env-info
      - run: just check
      - run: just check-doc

  # This final step is needed to mark the whole workflow as successful
  # Don't change its name - it is used by the merge protection rules
  done:
    name: CI Finished
    runs-on: ubuntu-latest
    needs: [ check, lint, unit-test ]
    if: always()
    permissions: {}
    steps:
      - name: Result of the needed steps
        run: echo "${{ toJSON(needs) }}"
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        name: CI Result
        run: exit 1
